# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
import torch
import torch.nn

class ISTDP:
    def __init__(self: Self, conn: Any, lr: Any, tau1: Any, tau2: Any, A: Any, beta: Any, a: Any, dt: Any) -> None: ...
    def initialize_traces(self: Self, batch: Any, num_pre: Any, num_post: Any, device: Any) -> Any: ...
    def reset_traces(self: Self) -> Any: ...
    def forward(self: Self, pre_spike_t: Any, post_spike_t: Any, return_more: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import torch
import torch.nn