# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
import torch
import torch.nn

class STD:
    def __init__(self: Self, in_dim: int, U: Any, tau_d: Any, dt: Any) -> None: ...
    def forward(self: Self, input_spike: Any) -> Any: ...
    def initialize_state(self: Self, batch_size: Any, device: Any) -> Any: ...
    def reset_state(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import torch
import torch.nn